apiVersion: v1
kind: Service
metadata:
  {{ if .Values.env_name }}
  name: 'furan-{{ .Values.service.name }}'
  {{- else }}
  name: {{ .Values.service.name }}
  {{- end }}
  labels:
    app: {{ template "consul.name" . }}
    chart: {{ template "consul.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.ports.internalPort }}
      protocol: TCP
      targetPort: {{ .Values.service.ports.externalPort }}
  selector:
    app: {{ template "consul.name" . }}
    release: {{ .Release.Name }}
